server:
  port: 8888

spring:
  zipkin:
    service:
      name: config-server-git
    base-url: ${ZIPKIN_URL}
    enabled: true
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/abdullahsokmen/config-server-repos6.git"
          default-label: main
          skip-ssl-validation: true
          username: abdullahsokmen
          password: ${GIT_JAVA6_KEY}