server:
  port: 80

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: auth
                fallbackUri: forward:/fallback/auth
        - id: product-service
          uri: https://localhost:9091
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product
                fallbackUri: forward:/fallback/product
        - id: sales-service
          uri: https://localhost:9292
          predicates:
            - Path=/sales/**
          filters:
            - name: CircuitBreaker
              args:
                name: sales
                fallbackUri: forward:/fallback/sales
        - id: user-service
          uri: https://localhost:9293
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: user
                fallbackUri: forward:/fallback/user
      default-filters:
        #         http://localhost/auth/findbyid/1
        #         (?<segment>.*) -> /auth/findbyid/1
        #       /$\{segment} -> http://localhost:9090/auth/findbyid1
        - RewritePath= /(?<segment>.*), /$\{segment}